project_name: 'Images'
experiment_name: 'experiment1'
dir_save_experiment: 'experiment'
n_epochs: 10
accelerator: 'cpu'
device: 1
monitor_metric: 'val_loss'
monitor_mode: 'min'

optimizer: 'torch.optim.SGD'
optimizer_kwargs:
  lr: 1e-3

scheduler: 'torch.optim.lr_scheduler.StepLR'
scheduler_kwargs:
  step_size: 2
  gamma: 0.98
  verbose: true

loss_fn: 'torch.nn.CrossEntropyLoss'

data_config:
  dataset_url: 'https://www.dropbox.com/scl/fi/nrn0y41dsfwqsrssav2eo/Classification_data.zip?rlkey=oieytodt749yzyippc6384tge&dl=1'
  dir_save: 'dataset'
  resize: 64
  batch_size: 2
  n_workers: 12
  train_size: 0.8
